# Generated by Django 3.1.7 on 2021-03-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrm', '0002_auto_20210331_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
