# Generated by Django 3.1.7 on 2021-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrm', '0003_auto_20210331_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='delivery_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='order_date',
            field=models.CharField(max_length=30),
        ),
    ]
