# Generated by Django 3.1.7 on 2021-04-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcrm', '0004_auto_20210331_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
